name = "WWI Industrial"
author = "Die 3 Musketiere"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a5fef603a1526d5e9f33b0a1e9f293d7af6840787d3d5a4285140c98ddffbd3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"
