name = "WWI Industrial"
author = "Die 3 Musketiere"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93aed4152ffae98eb2856907e5503bc50b665c67950a462822cd1f6b8b53951b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"
