name = "WWI Industrial"
author = "Die 3 Musketiere"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79732152dcd154174df8acc9a3deafcf2d660953c073b2c2e5205e201b2ad56a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"
